return {
	{ -- highlight, edit, and navigate code
		"nvim-treesitter/nvim-treesitter",
    dependencies = {
      'JoosepAlviste/nvim-ts-context-commentstring',
    },
		version = false,
		build = ":TSUpdate",
		event = "bufreadpost",
		keys = {
			{ "<s-space>", desc = "increment selection" },
			{ "<bs>", desc = "schrink selection", mode = "x" },
		},
		opts = {
      autotag = { enable = true },
      highlight = { enable = true, additional_vim_regex_highlighting = true, use_languagetree = true },
      indent = {
        enable = false,
      },
			ensure_installed = {
				"bash",
				"c",
				"c_sharp",
				"cmake",
				"comment",
				"cpp",
				"css",
				"diff",
				"dockerfile",
				"dot",
				"func",
				"gdscript",
				"godot_resource",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"glsl",
				"hlsl",
				"go",
				"gomod",
				"gowork",
				"gosum",
				"graphql",
				"vimdoc",
				"regex",
				"html",
				"http",
				"ini",
				"javascript",
				"jq",
				"jsdoc",
				"json",
				"jsonc",
				"json5",
				"llvm",
				"lua",
				"make",
				"markdown",
				"markdown_inline",
				"proto",
				"scss",
				"solidity",
				"todotxt",
				"tsx",
				"vim",
				"yaml",
				"sql",
				"typescript",
			},
		},
		config = function(_, opts)
			require("nvim-treesitter.configs").setup(opts)
		end,
	},
	-- { "nvim-treesitter/nvim-treesitter-textobjects", after = "nvim-treesitter" },
}
